name: build

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
    
      - name: Set ENV
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build
        run: go build -v -ldflags="${{ env.LDFLAGS }}" -o ./proxy-terminator ./cmd
        env:
          LDFLAGS: -X 'main.Version=${{ env.TAG_VERSION }}'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push
        run: docker build --push -t channyein87/linkerd-proxy-terminator:${{ env.TAG_VERSION }} .